select
comentario,
usuario,
ciudad,
puntaje,
fecha_viaje,
link,
PARSE_DATE('%Y%m%d',  CONCAT(ano,mes,'01')) date,
cast(CONCAT(ano,mes) as int64) ano_mes,
pais
from
(
SELECT
comentario,
usuario,
ciudad,
puntaje,
fecha_viaje,
link,
case
when fecha_viaje like '%enero%' then '01'
when fecha_viaje like '%febrero%' then '02'
when fecha_viaje like '%marzo%' then '03'
when fecha_viaje like '%abril%' then '04'
when fecha_viaje like '%mayo%' then '05'
when fecha_viaje like '%junio%' then '06'
when fecha_viaje like '%julio%' then '07'
when fecha_viaje like '%agosto%' then '08'
when fecha_viaje like '%septiembre%' then '09'
when fecha_viaje like '%octubre%' then '10'
when fecha_viaje like '%noviembre%' then '11'
when fecha_viaje like '%diciembre%' then '12'
end mes,
REGEXP_REPLACE(fecha_viaje, r'[^\d]+', '') ano,
case
when ciudad like '%Buenos Aires, Argentina%' then 'argentina'
when ciudad like '%Madrid, España%' then 'españa'
when ciudad like '%Barcelona, España%' then 'españa'
when ciudad like '%Provincia de Buenos Aires, Argentina%' then 'argentina'
when ciudad like '%Rosario, Argentina%' then 'argentina'
when ciudad like '%Buenos Aires%' then 'argentina'
when ciudad like '%Santiago, Chile%' then 'chile'
when ciudad like '%La Plata, Argentina%' then 'argentina'
when ciudad like '%Mar del Plata, Argentina%' then 'argentina'
when ciudad like '%Valencia, España%' then 'españa'
when ciudad like '%Montevideo, Uruguay%' then 'uruguay'
when ciudad like '%Córdoba, Argentina%' then 'argentina'
when ciudad like '%Distrito Capital Federal, Argentina%' then 'argentina'
when ciudad like '%Bogotá, Colombia%' then 'colombia'
when ciudad like '%Zaragoza, España%' then 'españa'
when ciudad like '%Argentina%' then 'argentina'
when ciudad like '%Sevilla, España%' then 'españa'
when ciudad like '%A Coruña, España%' then 'españa'
when ciudad like '%Palma de Mallorca, España%' then 'españa'
when ciudad like '%Ciudad de México, México%' then 'mexico'
when ciudad like '%Valladolid, España%' then 'españa'
when ciudad like '%Las Palmas de Gran Canaria, España%' then 'españa'
when ciudad like '%buenos aires%' then 'argentina'
when ciudad like '%Barcelona%' then 'españa'
when ciudad like '%Granada, España%' then 'españa'
when ciudad like '%España%' then 'españa'
when ciudad like '%San Isidro, Argentina%' then 'argentina'
when ciudad like '%San Sebastián - Donostia, España%' then 'españa'
when ciudad like '%Mendoza, Argentina%' then 'argentina'
when ciudad like '%Argentina central, Argentina%' then 'argentina'
when ciudad like '%Provincia de Córdoba, Argentina%' then 'argentina'
when ciudad like '%Pilar, Argentina%' then 'argentina'
when ciudad like '%Avellaneda, Argentina%' then 'argentina'
when ciudad like '%Santander, España%' then 'españa'
when ciudad like '%Bahia Blanca, Argentina%' then 'argentina'
when ciudad like '%Santa Fe, Argentina%' then 'argentina'
when ciudad like '%Santa Cruz de Tenerife, España%' then 'españa'
when ciudad like '%Azul, Argentina%' then 'argentina'
when ciudad like '%Pamplona, España%' then 'españa'
when ciudad like '%Castellón de la Plana, España%' then 'españa'
when ciudad like '%San Carlos de Bariloche, Argentina%' then 'argentina'
when ciudad like '%Lima, Perú%' then ''
when ciudad like '%Tenerife, España%' then 'españa'
when ciudad like '%Lanus, Argentina%' then 'argentina'
when ciudad like '%Región Metropolitana de Santiago, Chile%' then ''
when ciudad like '%Comunidad de Madrid, España%' then 'españa'
when ciudad like '%argentina%' then 'argentina'
when ciudad like '%Lomas de Zamora, Argentina%' then 'argentina'
when ciudad like '%Quilmes, Argentina%' then 'argentina'
when ciudad like '%Asuncion, Paraguay%' then ''
when ciudad like '%Bilbao, España%' then 'españa'
when ciudad like '%Alicante, España%' then 'españa'
when ciudad like '%Murcia, España%' then 'españa'
when ciudad like '%San Miguel de Tucuman, Argentina%' then 'argentina'
when ciudad like '%Sabadell, España%' then 'españa'
when ciudad like '%Tarragona, España%' then 'españa'
when ciudad like '%Sant Cugat del Vallès, España%' then 'españa'
when ciudad like '%Málaga, España%' then 'españa'
when ciudad like '%Toledo, España%' then 'españa'
when ciudad like '%Santa Tecla, La Libertad, El Salvador	el%' then 'salvador'
when ciudad like '%Guadalajara, España%' then 'españa'
when ciudad like '%madrid%' then 'españa'
when ciudad like '%Madrid, Spain%' then 'españa'
when ciudad like '%Córdoba, España%' then 'españa'
when ciudad like '%Neuquen, Argentina%' then 'argentina'
when ciudad like '%Provincia de Mendoza, Argentina%' then 'argentina'
when ciudad like '%Andorra la Vella, Andorra%' then 'andorra'
when ciudad like '%Cataluña, España%' then 'españa'
when ciudad like '%Salamanca, España%' then 'españa'
when ciudad like '%Buenos Aires, Distrito Federal, Argentina%' then 'argentina'
when ciudad like '%Fuenlabrada, España%' then 'españa'
when ciudad like '%Pozuelo de Alarcón, España%' then 'españa'
when ciudad like '%Vilanova i la Geltrú, España%' then 'españa'
when ciudad like '%Lugo, España%' then 'españa'
when ciudad like '%Tigre, Argentina%' then 'argentina'
when ciudad like '%El Puerto de Santa María, Andalucia, Spain%' then 'españa'
when ciudad like '%Puerto Rico	puerto%' then 'rico'
when ciudad like '%Arrecife, Spain%' then 'españa'
when ciudad like '%Provincia de Santa Fe, Argentina%' then 'argentina'
when ciudad like '%Cambrils, España%' then 'españa'
when ciudad like '%Mallorca, España%' then 'españa'
when ciudad like '%Igualada, España%' then 'españa'
when ciudad like '%Brisbane, Australia%' then 'australia'
when ciudad like '%Abu Dabi, Emiratos Árabes Unidos	emiratos%' then 'arabes'
when ciudad like '%La Rioja, Argentina%' then 'argentina'
when ciudad like '%Concepción, Chile%' then 'chile'
when ciudad like '%Nueva York, Estado de Nueva York	estados%' then 'unidos'
when ciudad like '%Madrid%' then 'españa'
when ciudad like '%Barcelona, Cataluña, Spain%' then 'españa'
when ciudad like '%Quilpué, Chile%' then 'chile'
when ciudad like '%Dubái, Emiratos Árabes Unidos	emiratos%' then 'arabes'
when ciudad like '%Vitoria-Gasteiz, España%' then 'españa'
when ciudad like '%Castelldefels, España%' then 'españa'
when ciudad like '%Santa Rosa, Argentina%' then 'argentina'
when ciudad like '%Burgos, España%' then 'españa'
when ciudad like '%Marbella, España%' then 'españa'
when ciudad like '%Gijón, España%' then 'españa'
when ciudad like '%barcelona%' then 'españa'
when ciudad like '%Necochea, Argentina%' then 'argentina'
when ciudad like '%Getxo, España%' then 'españa'
when ciudad like '%Provincia de Salta, Argentina%' then 'argentina'
when ciudad like '%Cáceres, España%' then 'españa'
when ciudad like '%Galicia%' then 'españa'
when ciudad like '%Mexico City, Mexico%' then 'mexico'
when ciudad like '%Cancún, México%' then 'mexico'
when ciudad like '%Denia, España%' then 'españa'
when ciudad like '%Ensenada, Argentina%' then 'argentina'
when ciudad like '%Guayaquil, Ecuador%' then 'ecuador'
when ciudad like '%León, España%' then 'españa'
when ciudad like '%Blanes, España%' then 'españa'
when ciudad like '%Saldaña, España%' then 'españa'
when ciudad like '%BARCELONA%' then 'españa'
when ciudad like '%Colon, Argentina%' then 'argentina'
when ciudad like '%Girona, España%' then 'españa'
when ciudad like '%Alcorcón, España%' then 'españa'
when ciudad like '%Chascomus, Argentina%' then 'argentina'
when ciudad like '%Monterrey, México%' then 'mexico'
when ciudad like '%Esplugues de Llobregat, España%' then 'españa'
when ciudad like '%Alicante%' then 'españa'
when ciudad like '%Moscú, Rusia%' then 'rusia'
when ciudad like '%Campello, España%' then 'españa'
when ciudad like '%Elche, España%' then 'españa'
when ciudad like '%Lisboa, Portugal%' then 'portugal'
when ciudad like '%L%Ametlla del Vallès, España%' then 'españa'
when ciudad like '%Vicente Lopez, Argentina%' then 'argentina'
when ciudad like '%Logroño, España%' then 'españa'
when ciudad like '%Reus, España%' then 'españa'
when ciudad like '%panama%' then 'panama'
when ciudad like '%Arequipa, Perú%' then 'peru'
when ciudad like '%Guaymallen-Mendoza%' then 'argentina'
when ciudad like '%Inca, España%' then 'españa'
when ciudad like '%Provincia de Barcelona, España%' then 'españa'
when ciudad like '%El Masnou, España%' then 'españa'
when ciudad like '%Cabrera de Mar, España%' then 'españa'
when ciudad like '%Malaga%' then 'malaga'
when ciudad like '%Puerto Madryn, Argentina%' then 'argentina'
when ciudad like '%El Escorial, España%' then 'españa'
when ciudad like '%Miami, Florida	estados%' then 'unidos'
when ciudad like '%Mataró, España%' then 'españa'
when ciudad like '%santiago chile%' then 'chile'
when ciudad like '%Cantón de Friburgo, Suiza%' then 'suiza'
when ciudad like '%Santa Cruz, Bolivia%' then 'bolivia'
when ciudad like '%Río de Janeiro, RJ%' then 'brasil'
when ciudad like '%Dubai	emiratos%' then 'arabes'
when ciudad like '%Lanús, Buenos Aires, Argentina%' then 'argentina'
when ciudad like '%Costa Rica	costa%' then 'rica'
when ciudad like '%ushuaia%' then 'argentina'
when ciudad like '%Ushuaia, Argentina%' then 'argentina'
when ciudad like '%Ronda, España%' then 'españa'
when ciudad like '%Cádiz, España%' then 'españa'
when ciudad like '%Salta, Argentina%' then 'argentina'
when ciudad like '%Santo Domingo, República Dominicana	republica%' then 'dominicana'
when ciudad like '%Campana, Argentina%' then 'argentina'
when ciudad like '%Lomas de Zamora, Buenos Aires, Argentina%' then 'argentina'
when ciudad like '%Resistencia, Argentina%' then 'argentina'
when ciudad like '%Ceuta, Andalucia, Spain%' then 'españa'
when ciudad like '%Gavà, España%' then 'españa'
when ciudad like '%MAR DEL PLATA%' then 'argentina'
when ciudad like '%Madrid, Comunidad de Madrid, Spain%' then 'españa'
when ciudad like '%Badajoz, España%' then 'españa'
when ciudad like '%Medellín, Colombia%' then 'colombia'
when ciudad like '%Provincia de Málaga, España%' then 'españa'
when ciudad like '%Salta%' then 'argentina'
when ciudad like '%arg%' then 'argentina'
when ciudad like '%Ourense, España%' then 'españa'
when ciudad like '%Viladecans, España%' then 'españa'
when ciudad like '%Algeciras, España%' then 'españa'
when ciudad like '%Metepec, México%' then 'mexico'
when ciudad like '%Spain%' then 'españa'
when ciudad like '%El Médano, España%' then 'españa'
when ciudad like '%Berazategui, Argentina%' then 'argentina'
when ciudad like '%Panama City%' then 'panama'
when ciudad like '%BADALONA%' then 'españa'
when ciudad like '%Quito, Ecuador%' then 'ecuador'
when ciudad like '%Florencia, Italia%' then 'italia'
when ciudad like '%ARGENTINA%' then 'argentina'
when ciudad like '%La Bisbal d%Empordà, España%' then 'españa'
when ciudad like '%Viedma, Argentina%' then 'argentina'
when ciudad like '%La Plata%' then 'argentina'
when ciudad like '%galicia ourense%' then 'españa'
when ciudad like '%Torrevieja, España%' then 'españa'
when ciudad like '%Manresa, España%' then 'españa'
when ciudad like '%Bogotá, Cundinamarca, Colombia%' then 'colombia'
when ciudad like '%Tortuguitas, Argentina%' then 'argentina'
when ciudad like '%argentina en EEUU(informacion en español	estados%' then 'unidos'
when ciudad like '%Conocoto, Ecuador%' then 'ecuadr'
when ciudad like '%Ferrol, España%' then 'españa'
when ciudad like '%Avilés, España%' then 'españa'
when ciudad like '%Olavarria, Argentina%' then 'argentina'
when ciudad like '%Cerdanyola del Vallès, España%' then 'españa'
when ciudad like '%Adrogue, Argentina%' then 'argentina'
when ciudad like '%Haro, España%' then 'españa'
when ciudad like '%Cornellà de Llobregat, España%' then 'españa'
when ciudad like '%Cancun%' then 'mexico'
when ciudad like '%Casilda, Argentina%' then 'argentina'
when ciudad like '%Playa de Muro, España%' then 'españa'
when ciudad like '%San Nicolas de los Arroyos, Argentina%' then 'argentina'
when ciudad like '%Vic, España%' then 'españa'
when ciudad like '%Buñuel, España%' then 'españa'
else ''
end pais
FROM `bigquery-prueba.data.scraping`
)